---
# tasks file for odoo-role

- name: Deploy Odoo using Docker Compose
  template:
    src: docker-compose.yml.j2
    dest: /home/{{ system_user }}/odoo-compose.yml
- name: Ensure Docker Compose is up 
  command: /usr/local/bin/docker-compose -f /home/{{ system_user }}/odoo-compose.yml up -d

    
