---
# defaults file for pgadmin-role
network_name: odoo_network
pgadmin_data_volume: pgadmin-data
pgadmin_mount_dir: /var/lib/pgadmin
pgadmin_service_name: pgadmin
pgadmin_container_name: pgadmin_container
pgadmin_listen_port: 5050
pgadmin_host_port: 5050
servers_json_path: /path/to/your/servers.json
system_user: ec2-user
