apiVersion: v1
kind: Secret
metadata:
  name: odoo-secret
  namespace: icgroup

  labels:
    app: odoo
    env: prod
type: Opaque
data:
  POSTGRES_HOST: cG9zdGdyZXM= # Base64 encoded value of 'postgres'
  POSTGRES_USER: YWRtaW4= # Base64 encoded value of 'admin'
  POSTGRES_PASSWORD: cm9vdA== # Base64 encoded value of 'root'
