apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: icgroup

  labels:
    app: pgadmin
    env: prod
spec:
  type: NodePort
  selector:
    app: pgadmin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30400
