apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin # Sets Deployment name
  namespace: icgroup

  labels:
    app: pgadmin
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4 # Sets Image
          ports:
            - containerPort: 80 # Exposes container port
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: olivierdja@yahoo.fr
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgadmin-secret
                  key: pgadmin-password
          # defines the volume to store the data

          volumeMounts:
            - name: pgadmin-data
              mountPath: /var/lib/pgadmin
      volumes:
        - name: pgadmin-data
          persistentVolumeClaim:
            claimName: pgadmin-pvc
