apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: icgroup

  labels:
    app: postgres
    env: prod
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: root
