---
- name: Install docker on all servers
  hosts: all
  become: true
  roles:
    - install-docker


- name: Install IC-Webapp and odoo on server1
  hosts: server1
  become: true
  roles:
    - ic-webapp-role
    - odoo-role


- name: Install pgadmin-role on server2
  hosts: server2
  become: true
  roles:
    - pgadmin-role

 
 
