all:
  hosts:
    server1:
      ansible_host: 18.209.164.52
      ansible_user: ec2-user
      ansible_ssh_private_key_file: private_key.pem
      ansible_python_interpreter: /usr/bin/python3

    server2:
      ansible_host: 3.91.11.28
      ansible_user: ec2-user
      ansible_ssh_private_key_file: private_key.pem
