all:
  hosts:
    server1:
      ansible_host: 54.80.148.196
      ansible_user: ec2-user
      ansible_ssh_private_key_file: private_key.pem
      ansible_python_interpreter: /usr/bin/python3

    server2:
      ansible_host: 54.162.242.21
      ansible_user: ec2-user
      ansible_ssh_private_key_file: private_key.pem
