all:
  hosts:
    server1:
      ansible_host: 54.237.237.43
      ansible_user: ec2-user
      ansible_ssh_private_key_file: private_key.pem
    server2:
      ansible_host: 54.162.243.118
      ansible_user: ec2-user
      ansible_ssh_private_key_file: private_key.pem
